### ISSUE TITLE
Intel Processor Trace support

### ISSUE THREAD

**Issue by icedevml** [tklengyel/drakvuf#989]
The issue to track inplementation of IPT support in DRAKVUF:

* [x] IPT support in `xen_helper` (#987)
* [x] Global breakpoint callback for IPT plugin (#988)
* [x] Event counter - sequential ID assigned to each trap occurrence (#1001)
* [x] IPT functions in `libdrakvuf` (#998)
* [x] IPT plugin (#1000 🚀 🍰 )

**Comment by icedevml** [comment]
I will finish the "TBD" PRs within few days. I propose to review them all at once, so the bigger picture of the implementation approach will be visible.

**Comment by tklengyel** [comment]
LGTM

**Comment by Id3aFly** [comment]
@icedevml Why do you [remove the execute_faulted_cb trap at the end](https://github.com/tklengyel/drakvuf/blob/22fe0bc69139bd2f68467b2bae0c9c87ef0d1837/src/plugins/ipt/ipt.cpp#L270)?

Wouldn't it be more helpful to keep it?
I assume the code to work like this:
- The first time a page is "used" MmAccessFault handles this. You use a trap (mm_access_fault_hook_cb) on MmAccessFault to get the virtual address and set up the second trap.
- This second trap mm_access_fault_return_hook_cb is called when the original code flow continues and MmAccessFault resolved the physical address, so you can grab that. Additionally you set up the third and last trap.
- This last trap execute_faulted_cb is called (prior) to an instruction fetch that belongs to the page/frame containing the virtual/physical address. This trap dumps the memory of the page and deletes itself.

If I got it right, you only dump the page content at the first time code gets executed at the page? Is this assumption correct?

What happens if I execute non-malicious code at first (which would cause the trap to delete), write my payload at this same page and execute it then? The plugin wouldn't dump that page content, would it?

**Comment by icedevml** [comment]
> If I got it right, you only dump the page content at the first time code gets executed at the page? Is this assumption correct?

Yes. This works if the page with machine code is modified **prior** to first execution. If different machine code is executed from the same page then it will not work properly. This is an intended current limitation. We are aiming to lift this in the next versions.

**Comment by manorit2001** [comment]
This issue is closed in (https://github.com/tklengyel/drakvuf/pull/1156). Right?

**Comment by icedevml** [comment]
right, thx
